version: '3.8'

services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: replicated_db
      MYSQL_USER: repl
      MYSQL_PASSWORD: replpass
    ports:
      - "3307:3306"
    volumes:
      - ./master/my.cnf:/etc/mysql/conf.d/my.cnf

  mysql-replica:
    image: mysql:8.0
    container_name: mysql-replica
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3308:3306"
    depends_on:
      - mysql-master
    volumes:
      - ./replica/my.cnf:/etc/mysql/conf.d/my.cnf
